### ISSUE TITLE
Simplify Permissions and Roles DB structure

### ISSUE THREAD

**Issue by connecteev** [LMS-Laravel/LMS-Laravel#25]
The Database has:
```
model_has_permissions
model_has_roles
```
This is not very intuitive and not standard across roles/permissions of other laravel packages, so it will make it harder for you guys to integrate 3rd party packages. Before we go to far, I suggest we convert the existing code to be more standard.

Suggest using permissions, roles, permission_role, users, etc

See attached schema and seeders for reference

[permissions_and_roles.zip](https://github.com/LMS-Laravel/LMS-Laravel/files/3563662/permissions_and_roles.zip)

**Comment by angelkurten** [comment]
The structure we currently have is fine, in fact it is supported by one of the most used permission packages from Laravel
