### ISSUE TITLE
Application Not Working

### ISSUE THREAD

**Issue by sin2san** [LMS-Laravel/LMS-Laravel#34]
Hi,
I have cloned this app and followed the same installation instruction. But i got issue as undefined offset 0 error. And also where can i find my view files ?

**Comment by angelkurten** [comment]
Pls share screenshot with error

See readme with step  for install [https://github.com/LMS-Laravel/LMS-Laravel/blob/master/readme.md](https://github.com/LMS-Laravel/LMS-Laravel/blob/master/readme.md)

**Comment by sin2san** [comment]
It's working fine. Messed up with PHP version. Appreciate your quick response. Is this is the beta version? How to get the full version?

**Comment by angelkurten** [comment]
Yes it's alpha version, actually working in a template for home

**Comment by sin2san** [comment]
Is this system is available for public. The full Learning Management System?

**Comment by angelkurten** [comment]
Yes, coming soon!

**Comment by sin2san** [comment]
Thank you. I really appreciate your response.
