### ISSUE TITLE
Google reCAPTCHA 

### ISSUE THREAD

**Issue by jole786** [LMS-Laravel/LMS-Laravel#39]
Any one tell me how do i enable the google reCAPTCHA.Because without that i am  not able to register the user and login user.

**Comment by vaishnavmhetre** [comment]
Recaptcha config might be tedious. for now, remove the google recaptcha validator from Login controller in Auth and login will work. Same will work for Register.

**Comment by vaishnavmhetre** [comment]
### Fixed in #40
