### ISSUE TITLE
Issue in migration

### ISSUE THREAD

**Issue by harshaldosh** [LMS-Laravel/LMS-Laravel#41]
Below migration issue recieved :

SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `migrations` (`migration`, `batch`) values (2016_06_01_000001_create_oauth_auth_codes_table, 4))

**Comment by angelkurten** [comment]
Solved in master branch

**Comment by harshaldosh** [comment]
Thanks,
I will check it out.
However, Just wanted to know can you put up *admin/username* password in
the github or landing page for  http://phpacademy.co/login

Regards,
Harshal
