### ISSUE TITLE
Target class [App\Services\Verifiers\MasterVerifier] does not exist.

### ISSUE THREAD

**Issue by nxame** [LMS-Laravel/LMS-Laravel#44]
Ran every thing as per readme.
Appp started.

On user registration, I get error:
Is this due to new sturcture change? Any help is appreciated!
![image](https://user-images.githubusercontent.com/3298585/80512828-d256dc00-899d-11ea-99c0-8b7d6f749f76.png)

**Comment by angelkurten** [comment]
Hi,

Pls pull new changes

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by nxame** [comment]
`
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Declaration of App\Exceptions\Handler::report(Exception $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) in /Users/shekhar/Sites/lms/app/Exceptions/Handler.php on line 9
PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
Stack trace:
0 /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): ReflectionClass->__construct('App\\Exceptions\\...')
1 /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->build('App\\Exceptions\\...')
2 /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array, false)
3 /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\Foundation\Application->resolve('App\\Exceptions\\...', Array, false)
4 /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php(801): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illu in /Users/shekhar/Sites/lms/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 807`

**Comment by angelkurten** [comment]
Yes, I forget push the last commit,  pls pull new changes

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by aalvarezv99** [comment]
Hola, acabé de hacer pull y de igual manera presenta el error, me hace falta algún paso?, gracias.
